name = "lfsync-example"
main = "src/index.ts"
compatibility_date = "2026-07-04"

[alias]
"@lfsync/example-definition" = "../example-definition/src/index.ts"
"@lsync/definitions" = "../../packages/definition/src/index.ts"

[[durable_objects.bindings]]
name = "SYNC_SHARDS"
class_name = "CollectionShard"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CollectionShard"]
