name = "lfsync-example"
main = "src/index.ts"
compatibility_date = "2026-07-04"

[[durable_objects.bindings]]
name = "SYNC_SHARDS"
class_name = "CollectionShard"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CollectionShard"]
