name = "lfsync-example"
main = "src/index.ts"
compatibility_date = "2026-07-04"

[[durable_objects.bindings]]
name = "LFSYNC_ROOMS"
class_name = "LfsyncRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LfsyncRoom"]

